// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bphxokvyjjgeeqqspalw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwaHhva3Z5ampnZWVxcXNwYWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjEyNDQsImV4cCI6MjA1OTA5NzI0NH0.u0aGtS1TTxsq1d6sqlUeuL2-m8SxOjzCoO1n08FNENc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);